{% set name = "pybsm" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybsm-{{ version }}.tar.gz
  sha256: ef6672ee5d496bc7d9d54fffe088fa58a0691a48578ab25bcb518588cca85593

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.22,<1.26  # [py<312]
    - numpy >=1.26,<2.0  # [py>=312]
    - matplotlib-base >=3.5.2
    - scipy <1.11.1  # [py<39]
    - scipy >=1.10.0,<1.14  # [py>=39]
    - py-opencv >=4.6.0

test:
  imports:
    - pybsm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pybsm/
  summary: 'This repo builds off of the work done by LeMaster and Eismann in creating the original pyBSM package for modeling image systems as well as LeMaster, et al. in their work in validating the pyBSM package'
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - bjrichardwebster
    - barry-ravichandran
    - Purg
