{% set name = "pybsm" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybsm-{{ version }}.tar.gz
  sha256: 020a7cddd79d55bba734037e16ad3d5b3072f8d4a44051516227844a62e0f75f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.22,<1.26  # [py<312]
    - numpy >=1.26,<2.0  # [py>=312]
    - matplotlib-base >=3.5.2
    - scipy <1.11.1  # [py<39]
    - scipy >=1.10.0,<1.14  # [py>=39]

test:
  imports:
    - pybsm
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: pybsm

  - name: pybsm-graphics
    requirements:
      host:
        - python
      run:
        - python
        - py-opencv >=4.6.0
        - {{ pin_subpackage('pybsm', exact=True) }}
    test:
      imports:
        - pybsm-graphics

  - name: pybsm-headless
    requirements:
      host:
        - python
      run:
        - python
        - opencv-python-headless >=4.6.0
        - {{ pin_subpackage('pybsm', exact=True) }}
    test:
      imports:
        - pybsm-headless

about:
  home: https://pypi.org/project/pybsm/
  summary: 'This repo builds off of the work done by LeMaster and Eismann in creating the original pyBSM package for modeling image systems as well as LeMaster, et al. in their work in validating the pyBSM package'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bjrichardwebster
    - barry-ravichandran
    - Purg
