{% set name = "pybsm" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybsm-{{ version }}.tar.gz
  sha256: 2f922823ec7db869e651d321d0f6ae2155303aa7e52e666ebe0a5c5428a15841

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry-core
  run:
    - python >=3.8,<4.0
    - numpy >=1.23.1,<1.25  # [py<312]
    - numpy >=1.25  # [py>=312]
    - matplotlib-base >=3.5.2,<4.0.0
    - scipy >=1.8.1,<1.9  # [py<311]
    - scipy >=1.9  # [py>=311]
    - py-opencv >=4.6.0,<5.0.0

test:
  imports:
    - pybsm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pybsm/
  summary: 'This repo builds off of the work done by LeMaster and Eismann in creating the original pyBSM package for modeling image systems as well as LeMaster, et al. in their work in validating the pyBSM package'
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - bjrichardwebster
    - barry-ravichandran
    - Purg
