{% set name = "pybsm" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybsm-{{ version }}.tar.gz
  sha256: d6f267ef3163bba94b805717dda67588db3a47ef8b28c72b0d19a08b0a7904c0

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.22,<2.0  # [py<=312]
    - numpy >=2.1  # [py>312]
    - matplotlib-base >=3.5.2
    - scipy >=1.10.0
    - setuptools >=78.1.1
    - numba ~=0.62.1

test:
  imports:
    - pybsm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pybsm/
  summary: 'This repo builds off of the work done by LeMaster and Eismann in creating the original pyBSM package for modeling image systems as well as LeMaster, et al. in their work in validating the pyBSM package'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephencrowell
    - eveenhuis
    - bjrichardwebster
    - barry-ravichandran
    - Purg
